// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataStorageCore.Models;

public partial class Archive
{
    public int Id { get; set; }

    public int MeasurumentId { get; set; }

    public DateTime Dt { get; set; }

    public double? Value { get; set; }

    public virtual Measurement Measurument { get; set; }
}