// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataStorageCore.Models;

public partial class Device
{
    public int Id { get; set; }

    public string SerialNumber { get; set; }

    public int DeviceTypeId { get; set; }

    public string NetAdress { get; set; }

    public virtual DeviceType DeviceType { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<Measurement> Measurements { get; set; } = new List<Measurement>();
}