// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataStorageCore.Domain;
using System;
using System.Collections.Generic;

namespace DataStorageCore.Models;

public partial class DeviceType: BaseEntity
{ 
    public string Name { get; set; }

    public virtual ICollection<Device> Devices { get; set; } = new List<Device>();
}