// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataStorageCore.Domain;
using System;
using System.Collections.Generic;

namespace DataStorageCore.Models;

public partial class EventDict : BaseEntity
{   
    public string Name { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}