// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataStorageCore.Domain;
using System;
using System.Collections.Generic;

namespace DataStorageCore.Models;

public partial class Event : BaseEntity
{   
    public int EventDictId { get; set; }

    public int DeviceId { get; set; }

    public DateTime Dt { get; set; }

    public virtual Device Device { get; set; }

    public virtual EventDict EventDict { get; set; }
}